const Users = () => {
    return [
        {
            "username": "User101",
            "businessEmail": "user101@techplace.com",
            "password": "password123!",
            "storeName": "Manchester, UK",
            "employeeId": "101-BC-2345-MAN",
            "currentPosition": "Admin",
            "role": "Admin",
        },
        {
            "username": "User102",
            "businessEmail": "user102@techville.com",
            "password": "SecurePass456",
            "storeName": "Birmingham, UK",
            "employeeId": "102-CD-5678-BIR",
            "currentPosition": "Sales",
            "role": "Seller",
        },
        {
            "username": "User103",
            "businessEmail": "user103@technode.com",
            "password": "NewPass789",
            "storeName": "Leeds, UK",
            "employeeId": "103-DE-8910-LEE",
            "currentPosition": "Manager",
            "role": "Supervisor",
        },
        {
            "username": "User104",
            "businessEmail": "user104@techhub.com",
            "password": "Pass123Tech",
            "storeName": "Glasgow, UK",
            "employeeId": "104-EF-1234-GLA",
            "currentPosition": "Technician",
            "role": "Technical Support",
        },
        {
            "username": "User105",
            "businessEmail": "user105@techworld.com",
            "password": "Password105",
            "storeName": "Liverpool, UK",
            "employeeId": "105-FG-5678-LIV",
            "currentPosition": "HR",
            "role": "Administrate",
        },
        {
            "username": "User106",
            "businessEmail": "user106@techline.com",
            "password": "Secure106",
            "storeName": "Sheffield, UK",
            "employeeId": "106-GH-9101-SHE",
            "currentPosition": "Finance",
            "role": "Financial",
        },
        {
            "username": "User107",
            "businessEmail": "user107@techflow.com",
            "password": "Password107",
            "storeName": "Newcastle, UK",
            "employeeId": "107-HI-1123-NEW",
            "currentPosition": "Marketing",
            "role": "Supplier",
        },
        {
            "username": "User108",
            "businessEmail": "user108@techwave.com",
            "password": "Pass108",
            "storeName": "Bristol, UK",
            "employeeId": "108-IJ-2345-BRI",
            "currentPosition": "Operations",
            "role": "Administrate",
        },
        {
            "username": "User109",
            "businessEmail": "user109@techtrend.com",
            "password": "Secure109",
            "storeName": "Cardiff, UK",
            "employeeId": "109-JK-3456-CAR",
            "currentPosition": "Logistics",
            "role": "Administrate",
        },
        {
            "username": "User110",
            "businessEmail": "user110@techpioneer.com",
            "password": "Pass110",
            "storeName": "Edinburgh, UK",
            "employeeId": "110-KL-4567-EDI",
            "currentPosition": "Customer Support",
            "role": "Technical Support",
        }
    ];
};

export default Users;
